config/routes.rb
Gaku::Core::Engine.routes.draw  do

  concern(:pagination)      { get 'page/:page', action: :index, on: :collection }
  concern :soft_delete do
    patch :recovery,    on: :member
    patch :soft_delete, on: :member
  end

  resources :attachments, concerns: :soft_delete
  resources :teachers, concerns: :soft_delete
  resources :students, concerns: :soft_delete do
    get :search, on: :collection
    get :clear_search, on: :collection
    get :advanced_search, on: :collection
    get :chosen, on: :collection
    resources :guardians, concerns: :soft_delete
  end

  resources :student_selection, only: :index do
    collection do
      get :clear
      post :add
      post :remove
    end
  end

  resources :extracurricular_activities, concerns: :soft_delete
  resources :class_groups, concerns: :soft_delete do
    collection do
      get :search
      get :search_semester
      get :advanced_search
      get :semester_advanced_search
      get :with_semester
      get :without_semester
    end
  end
  resources :courses, concerns: :soft_delete
  resources :course_groups, concerns: :soft_delete
  resources :exams, concerns: :soft_delete
  resources :syllabuses, concerns: :soft_delete

  namespace :admin do

    resources :students, only: :show

    namespace :changes do
      resources :students, controller: 'student_changes', concerns: %i( pagination )
      resources :student_contacts,  controller: 'student_contact_changes'
      resources :student_addresses, controller: 'student_address_changes'
    end

    resources :disposals do
      collection do
        get :students
        get :teachers
        get :guardians
        get :exams
        get :course_groups
        get :attachments
        get :addresses
        get :contacts

        get 'students/page/:page',      action: :students
        get 'teachers/page/:page',      action: :teachers
        get 'guardians/page/:page',     action: :guardians
        get 'exams/page/:page',         action: :exams
        get 'course_groups/page/:page', action: :course_groups
        get 'attachments/page/:page',   action: :attachments
        get 'addresses/page/:page',     action: :addresses
        get 'contacts/page/:page',      action: :contacts
      end
    end

  end
end

app/controllers/gaku/admin/changes/student_address_changes_controller.rb
module Gaku
  class Admin::Changes::StudentAddressChangesController < Admin::BaseController

    # load_and_authorize_resource class: PaperTrail::Version

    respond_to :html

    def index
      @changes = Gaku::Versioning::AddressVersion.student_addresses
      @count = Gaku::Versioning::AddressVersion.student_addresses.count
    end

  end
end

app/controllers/gaku/admin/changes/student_changes_controller.rb
module Gaku
  class Admin::Changes::StudentChangesController < Admin::BaseController

    # load_and_authorize_resource class: StudentVersion
    respond_to :html, only: :index

    def index
      @count = Gaku::Versioning::StudentVersion.count
      @changes = Kaminari.paginate_array(Gaku::Versioning::StudentVersion.all).page(params[:page])
    end

  end
end

app/controllers/gaku/admin/changes/student_contact_changes_controller.rb
module Gaku
  class Admin::Changes::StudentContactChangesController < Admin::BaseController

    # load_and_authorize_resource class: PaperTrail::Version
    respond_to :html

    def index
      @changes = Gaku::Versioning::ContactVersion.student_contacts
      @count = Gaku::Versioning::ContactVersion.student_contacts.count
    end

  end
end

app/views/gaku/admin/changes/student_address_changes/_change.html.slim
- change.changeset.keys.each do |key|
  tr
    td = change.id
    td = link_to "#{t(:'student.singular')} #{change.joined_resource_id}", admin_student_path(change.joined_resource_id)
    td = change.event
    td = key
    td = change.changeset[key][0]
    td = change.changeset[key][1]
    td = change.whodunnit
    td = change.created_at

app/views/gaku/admin/changes/student_address_changes/_changes.html.slim
= sortable_table_for 'admin-student-address-changes-index' do
  thead
    tr
      = th_icon 'check'
      = th t(:'student.singular')
      = th t(:'changes.event')
      = th t(:'changes.change')
      = th t(:'changes.from')
      = th t(:'changes.to')
      = th t(:'changes.user')
      = th t(:'changes.changed_at')

  tbody
    - @changes.each do |change|
      - if change.event == 'destroy'
        = render 'deletion', change: change
      - else
        = render 'change', change: change

app/views/gaku/admin/changes/student_address_changes/_deletion.html.slim
tr
  td = change.id
  td = link_to "#{t(:'student.singular')} #{change.joined_resource_id}", admin_student_path(change.joined_resource_id)
  td = change.event
  td
  td
  td
  td = change.whodunnit
  td = change.created_at

app/views/gaku/admin/changes/student_address_changes/index.html.slim
= content_for :title, t(:'changes.student_address.list')

= content_for :index_header do
  .pull-left
    = count_div 'changes-count' do
      = print_count @count, t(:'changes.student_address.list')

= hr

#changes-index
  = render 'changes'