config/routes.rb
Gaku::Core::Engine.routes.draw  do

  concern(:pagination)      { get 'page/:page', action: :index, on: :collection }
  concern :soft_delete do
    patch :recovery,    on: :member
    patch :soft_delete, on: :member
  end

  resources :attachments, concerns: :soft_delete
  resources :teachers, concerns: :soft_delete
  resources :students, concerns: :soft_delete do
    get :search, on: :collection
    get :clear_search, on: :collection
    get :advanced_search, on: :collection
    get :chosen, on: :collection
    resources :guardians, concerns: :soft_delete
  end

  resources :student_selection, only: :index do
    collection do
      get :clear
      post :add
      post :remove
    end
  end

  resources :extracurricular_activities, concerns: :soft_delete
  resources :class_groups, concerns: :soft_delete do
    collection do
      get :search
      get :search_semester
      get :advanced_search
      get :semester_advanced_search
      get :with_semester
      get :without_semester
    end
  end
  resources :courses, concerns: :soft_delete
  resources :course_groups, concerns: :soft_delete
  resources :exams, concerns: :soft_delete
  resources :syllabuses, concerns: :soft_delete

  namespace :admin do

    resources :students, only: :show

    namespace :changes do
      resources :students, controller: 'student_changes', concerns: %i( pagination )
      resources :student_contacts,  controller: 'student_contact_changes'
      resources :student_addresses, controller: 'student_address_changes'
    end

    resources :disposals do
      collection do
        get :students
        get :teachers
        get :guardians
        get :exams
        get :course_groups
        get :attachments
        get :addresses
        get :contacts

        get 'students/page/:page',      action: :students
        get 'teachers/page/:page',      action: :teachers
        get 'guardians/page/:page',     action: :guardians
        get 'exams/page/:page',         action: :exams
        get 'course_groups/page/:page', action: :course_groups
        get 'attachments/page/:page',   action: :attachments
        get 'addresses/page/:page',     action: :addresses
        get 'contacts/page/:page',      action: :contacts
      end
    end

  end
end

app/models/gaku/disposal.rb
module Gaku
  class Disposal
    class << self

      def students
        Student.unscoped.deleted
      end

      def teachers
        Teacher.unscoped.deleted
      end

      def guardians
        Guardian.unscoped.deleted
      end

      def exams
        Exam.unscoped.deleted
      end

      def course_groups
        CourseGroup.unscoped.deleted
      end

      def attachments
        Attachment.includes(:attachable).unscoped.deleted
      end

      def student_addresses
        Address.includes(:addressable, :country).unscoped.deleted.students
      end

      def teacher_addresses
        Address.includes(:addressable, :country).unscoped.deleted.teachers
      end

      def student_contacts
        Contact.includes(:contactable, :contact_type).unscoped.deleted.students
      end

      def teacher_contacts
        Contact.includes(:contactable, :contact_type).unscoped.deleted.teachers
      end

    end
  end
end

app/controllers/gaku/admin/disposals_controller.rb
module Gaku
  class Admin::DisposalsController < Admin::BaseController

    authorize_resource class: false

    def index

    end

    def students
      @students = Disposal.students.page(params[:page])
    end

    def teachers
      @teachers = Disposal.teachers.page(params[:page])
    end

    def guardians
      @guardians = Disposal.guardians.page(params[:page])
    end

    def exams
      @exams = Disposal.exams.page(params[:page])
    end

    def course_groups
      @course_groups = Disposal.course_groups.page(params[:page])
    end

    def attachments
      @attachments = Disposal.attachments.page(params[:page])

    end

    def addresses
      @student_addresses = Disposal.student_addresses.page(params[:page])
      @teacher_addresses = Disposal.teacher_addresses.page(params[:page])
      set_student_and_teacher_count('Gaku::Address')
    end

    def contacts
      @student_contacts = Disposal.student_contacts.page(params[:page])
      @teacher_contacts = Disposal.teacher_contacts.page(params[:page])
      set_student_and_teacher_count('Gaku::Contact')
    end

    private

    def set_student_and_teacher_count(klass)
      @students_count = klass.constantize.unscoped.deleted.students.count
      @teachers_count = klass.constantize.unscoped.deleted.teachers.count
    end

  end
end

app/views/gaku/admin/disposals/_address.html.slim
tr
  td = address.addressable
  td = address.title
  td = address.country
  td = address.zipcode
  td = address.state
  td = address.city
  td = address.address1
  td = address.address2
  td
    = ajax_link_to_restore [:recovery, address.addressable, address]
    = ajax_link_to_delete [address.addressable, address]

app/views/gaku/admin/disposals/_contact.html.slim
tr
  td = contact.contactable
  td = contact.name
  td = contact.data
  td = contact.details
  td = t(:'contact.emergency') if contact.emergency?
  td
    = ajax_link_to_restore [:recovery, contact.contactable, contact]
    = ajax_link_to_delete [contact.contactable, contact]

app/views/gaku/admin/disposals/_contacts.html.slim
= well_div do
  = table_for 'admin-student-contacts-disposals-index' do
    thead
      tr
        = th 'Person'
        = th t(:'contact.contact_type')
        = th t(:'contact.data')
        = th t(:'contact.details')
        = th t(:'contact.emergency')
        = th_actions 2
    tbody
      =render partial: 'contact', collection: disposals, as: :contact

  = paginate disposals

app/views/gaku/admin/disposals/_course_group.html.slim
tr
  td = course_group.name
  td

app/views/gaku/admin/disposals/_exam.html.slim
- unless exam.nil? or exam.new_record? or !exam
  tr
    td = exam.name
    td = exam.description
    td = exam.adjustments
    td = exam.weight
    td = exam.use_weighting
    td
      = ajax_link_to_restore [:recovery, exam]
      = ajax_link_to_delete exam

app/views/gaku/admin/disposals/_guardian.html.slim
tr
  td = guardian.surname
  td = guardian.name
  td = guardian.surname_reading
  td = guardian.name_reading
  td = guardian.birth_date
  td
    /= link_to_show [:show_deleted, guardian]
    /= link_to content_tag(:li, nil, class: 'icon-white icon-repeat'), [:recovery, guardian], class: 'mr-xs btn btn-mini btn-warning recovery-link', remote: true
    /= ajax_link_to_delete guardian , id: 'delete-disposal-guardian-link'

app/views/gaku/admin/disposals/_student.html.slim
tr
  td = student.surname
  td = student.name
  td = student.surname_reading
  td = student.name_reading
  td = student.birth_date
  td
    = link_to_show [:admin, student]
    = ajax_link_to_restore [:recovery, student]
    = ajax_link_to_delete student

app/views/gaku/admin/disposals/_tabs.html.slim
ul.nav.nav-tabs
  li.active
    = link_to(t(:'student.plural'), students_admin_disposals_path, id: 'students-tab-link')
  li
    = link_to(t(:'teacher.plural'), teachers_admin_disposals_path, id: 'teachers-tab-link')
  li
    = link_to(t(:'guardian.plural'), guardians_admin_disposals_path, id: 'guardians-tab-link')
  li
    = link_to(t(:'address.plural'), addresses_admin_disposals_path, id: 'addresses-tab-link')
  li
    = link_to(t(:'contact.plural'), contacts_admin_disposals_path, id: 'contacts-tab-link')
  li
    = link_to(t(:'exam.plural'), exams_admin_disposals_path, id: 'exams-tab-link')
  li
    = link_to(t(:'course_group.plural'), course_groups_admin_disposals_path, id: 'course-groups-tab-link')
  li
    = link_to(t(:'attachment.plural'), attachments_admin_disposals_path, id: 'attachments-tab-link')

app/views/gaku/admin/disposals/addresses.html.slim
= render 'tabs'
= render partial: 'gaku/admin/disposals/tabs/addresses_tabs', locals: { student_addresses: @student_addresses, teacher_addresses: @teacher_addresses }

app/views/gaku/admin/disposals/attachments.html.slim
= render 'tabs'

= well_div do
  = table_for 'disposal-attachments-index' do
    thead
      tr
        = th t(:'attachment.name')
        = th t(:'attachment.description')
        = th t(:'attachment.asset_type')
        = th t(:'resource')
        = th t(:'attachment.file_name')
        = th t(:'attachment.file_type')
        = th t(:'attachment.file_size')
        = th_actions 2
    tbody
      - @attachments.each do |attachment|
        tr
          td = attachment.name
          td = attachment.description
          td = attachment.attachable_type
          td = attachment.attachable
          td = attachment.asset_file_name
          td = attachment.asset_content_type
          td = number_to_human_size attachment.asset_file_size
          td
            = ajax_link_to_restore [:recovery, attachment]
            = ajax_link_to_delete attachment


  = paginate @attachments

app/views/gaku/admin/disposals/course_groups.html.slim
= render 'tabs'

= well_div do
  = table_for 'disposal-course-group-index' do
    thead
      tr
        = th t(:'course_group.name')
        = th_actions 3
    tbody
      = render partial: 'course_group', collection: @course_groups, as: :course_group

  = paginate @course_groups

app/views/gaku/admin/disposals/guardians.html.slim
= render 'tabs'

= well_div do
  = table_for 'disposal-guardian-index' do
    thead
      tr
        = th t(:'surname')
        = th t(:'name')
        = th t(:'surname_reading')
        = th t(:'name_reading')
        = th t(:'birth_date')
        = th_actions 3
    tbody
      = render partial: 'guardian', collection: @guardians, as: :guardian

  = paginate @guardians

app/views/gaku/admin/disposals/index.html.slim
= render 'tabs'

app/views/gaku/admin/disposals/students.html.slim
= render 'tabs'

= well_div do
  = table_for 'disposal-student-index' do
    thead
      tr
        = th t(:'surname')
        = th t(:'name')
        = th t(:'surname_reading')
        = th t(:'name_reading')
        = th t(:'birth_date')
        = th_actions 3
    tbody
      = render partial: 'student', collection: @students, as: :student

  = paginate @students